apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envoy.labels" . | nindent 4 }}
data:
  envoy.yaml: |- {{ include "envoy.config" . | nindent 4 }}
