apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: todo
spec:
  fleet:  
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  # service name and port should be specified inside x-kusk annotation
  spec: |
    openapi: 3.0.0
    info:
      title: Todo-Backend API
      version: 1.0.0
    x-kusk:
      cors:
        origins:
          - '*'
        methods:
          - POST
          - PATCH
          - DELETE
          - PUT
          - GET
          - OPTIONS
        headers:
          - Content-Type
        credentials: true
        max_age: 86200
      upstream:
        service:
          namespace: default
          name: todo-backend
          port: 3000
      path:
        prefix: /
    paths:
      /todos/{id}:
        get:
          responses:
            '200':
              description: ''
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      title:
                        type: string
                        description: Description of what to do
                      completed:
                        type: boolean
                      order:
                        type: integer
                        format: int32
                      url:
                        type: string
                    required:
                      - title
                      - completed
                      - order
                      - url
            '400':
              description: Client error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
            '500':
              description: Server error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
          summary: Shows a single Todo
          parameters:
            - name: id
              in: path
              schema:
                type: integer
              required: true
          tags:
            - Todo
        delete:
          responses:
            '200':
              description: ''
            '400':
              description: Client error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
            '500':
              description: Server error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
          summary: Deletes this Todo
          parameters:
            - name: id
              in: path
              schema:
                type: integer
              required: true
          tags:
            - Todo
        patch:
          x-kusk:
            validation:
              request:
                enabled: true
          responses:
            '200':
              description: ''
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      title:
                        type: string
                        description: Description of what to do
                      completed:
                        type: boolean
                      order:
                        type: integer
                        format: int32
                      url:
                        type: string
                    required:
                      - title
                      - completed
                      - order
                      - url
            '400':
              description: Client error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
            '500':
              description: Server error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
          summary: Modifies this Todo
          parameters:
            - name: id
              in: path
              schema:
                type: integer
              required: true
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  # if you want strict validation of request bodies, please enable this option in your OpenAPI file
                  additionalProperties: false
                  properties:
                    title:
                      type: string
                    completed:
                      type: boolean
                    order:
                      type: integer
                      format: int32
          tags:
            - Todo
      /todos:
        get:
          responses:
            '200':
              description: The full list of todos
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: Description of what to do
                        completed:
                          type: boolean
                        order:
                          type: integer
                          format: int32
                        url:
                          type: string
                      required:
                        - title
                        - completed
                        - order
                        - url
            '400':
              description: Client error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
            '500':
              description: Server error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
          summary: Lists all Todos
          description: The returned Todos are ordered by 'order' and then 'title'
          tags:
            - Todo
        post:
          responses:
            '201':
              description: ''
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      title:
                        type: string
                        description: Description of what to do
                      completed:
                        type: boolean
                      order:
                        type: integer
                        format: int32
                      url:
                        type: string
                    required:
                      - title
                      - completed
                      - order
                      - url
            '400':
              description: Client error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
            '500':
              description: Server error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
          summary: Creates a new, uncompleted Todo
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    title:
                      type: string
                      description: Description of what to do
                    order:
                      type: integer
                      format: int32
                  required:
                    - title
          tags:
            - Todo
        delete:
          responses:
            '200':
              description: ''
            '400':
              description: Client error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
            '500':
              description: Server error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/endpoints.Errors'
          summary: Deletes all Todos
          tags:
            - Todo
    components:
      schemas:
        endpoints.Errors:
          type: array
          items:
            type: string
