before:
  hooks:
    - go mod tidy
    - go mod verify
builds:
  - id: kusk-gateway
    skip: true
  - id: kusk
    main: ./cmd/kusk/
    env:
      - CGO_ENABLED=0
    binary: kusk
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -w -s
      - -X 'github.com/kubeshop/kusk-gateway/pkg/build.Version={{.Env.VERSION}}'
      - -X github.com/kubeshop/kusk-gateway/pkg/analytics.TelemetryToken={{.Env.TELEMETRY_TOKEN}}
archives:
  - replacements:
      darwin: macOS
      linux: Linuxs
      windows: Windows
      386: i386
      amd64: x86_64
    id: kusk
    name_template: "kusk_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}"
    builds:
    - kusk
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  # Create a thread in the General category in the repo's discussion tab.
  discussion_category_name: General

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # Tags that have the format v1.0.0-rc1 will mark the release as a pre-release (i.e. not ready for production)
  # Other tags will be marked as ready for production
  prerelease: auto

brews:
  - tap:
      owner: kubeshop
      name: homebrew-kusk
    description: Make your OpenAPI definition the source of truth for API resources in cluster
    homepage: https://kusk.io
    license: "MIT"
    name: kusk
    install: bin.install "kusk"
    ids:
    - kusk