builds:
  - builder: prebuilt
    id: kusk
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    goamd64:
      - v1
    prebuilt:
      path: '{{ .Os }}/kusk_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/kusk{{ .Ext }}'
    binary: kusk
    hooks:
      pre: 'du -hs {{ .Os }}/kusk_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/kusk{{ .Ext }}'
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # Create a thread in the General category in the repo's discussion tab.
  discussion_category_name: General

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # Tags that have the format v1.0.0-rc1 will mark the release as a pre-release (i.e. not ready for production)
  # Other tags will be marked as ready for production
  prerelease: auto

brews:
  - tap:
      owner: kubeshop
      name: homebrew-kusk
    description: Make your OpenAPI definition the source of truth for API resources in cluster
    homepage: https://kusk.io
    license: "MIT"
    name: kusk
    install: bin.install "kusk"
    ids:
    - kusk

nfpms:
  - maintainer: Kusk Team
    package_name: kusk
    builds:
      - kusk
    license: "MIT"
    formats:
      - deb
    description: Kusk - Make your OpenAPI definition the source of truth for API resources in cluster
