version: "3.7"
services:
  petstore:
    container_name: petstore
    image: swaggerapi/petstore3:unstable
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.3"
  # kusk-gateway as a container will start only with: docker-compose up --profile "all"
  kusk-gateway:
    profiles: [ "gateway", "all" ]
    container_name: kusk-gateway
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "--in"
      - "/petshop-openapi-short-with-kusk-and-mock.yaml"
    volumes:
      - ./development/petshop-openapi-short-with-kusk-and-mock.yaml:/petshop-openapi-short-with-kusk-and-mock.yaml
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.4"
  front-envoy-cluster1-1:
    container_name: front-envoy-cluster1-1
    build:
      context: ./development/envoy
    environment:
      GO_CONTROL_PLANE_ADDRESS: ${GO_CONTROL_PLANE_ADDRESS}
      GO_CONTROL_PLANE_PORT: ${GO_CONTROL_PLANE_PORT}
      ENVOY_CLUSTER_ID: "default"
    ports:
      - 8080:8080
      - 19000:19000
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.5"
    volumes:
      - ./development/envoy/envoy.yaml.tmpl:/etc/envoy/envoy.yaml.tmpl
    depends_on:
      - petstore
    # Another Envoy in case one wants to test different clusters
    # - kusk-gateway
    # front-envoy-cluster1-2:
    #   container_name: front-envoy-cluster2-1
    #   build:
    #     context: ./development/envoy
    #   environment:
    #     GO_CONTROL_PLANE_ADDRESS: ${GO_CONTROL_PLANE_ADDRESS}
    #     GO_CONTROL_PLANE_PORT: ${GO_CONTROL_PLANE_PORT}
    #     ENVOY_CLUSTER_ID: "envoy_cluster2"
    #   ports:
    #     - 8081:8080
    #     - 19001:19000
    #   networks:
    #     kusk-gateway:
    #       ipv4_address: "172.21.0.6"
    #   volumes:
    #     - ./development/envoy/envoy.yaml.tmpl:/etc/envoy/envoy.yaml.tmpl
    #   depends_on:
    #     - petstore
    #     - kusk-gateway

    # This container is used during mocking testing
  "openapi-mock":
    container_name: "openapi-mock"
    image: muonsoft/openapi-mock
    # entrypoint: [ "tail", "-f", "/dev/null" ]
    profiles: [ "mock", "all" ]
    command:
      - "serve"
    volumes:
      - ./development/petshop-openapi-short-with-kusk-and-mock.yaml:/openapi.yaml
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/openapi.yaml'
    ports:
      - "8082:8080"
    networks:
      kusk-gateway:
        ipv4_address: "172.21.0.10"

networks:
  kusk-gateway:
    name: "kusk-gateway"
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

