site_name: Kusk Gateway
site_description: 'OpenAPI for Kubernetes done right'
site_author: 'Kubeshop Kusk team'
docs_dir: docs/
repo_name: 'kubeshop/kusk-gateway'
repo_url: 'https://github.com/kubeshop/kusk-gateway'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
  # features:
  #   - navigation.expand
nav:
  - Welcome: index.md
  - 'Getting Started': 
    - Installing Kusk Gateway: getting-started/installation.md
    - Deploy an OpenAPI definition: getting-started/deploy-an-api.md
    - Connect a Service to the API: getting-started/connect-a-service-to-the-api.md
  - 'Guides':
      - OpenAPI Extension: guides/working-with-extension.md
      - Mocking: guides/mocking.md
      - Validation: guides/validation.md
      - CORS: guides/cors.md
      - Routing & Disabling: guides/routing.md
      - Timeouts: guides/timeouts.md
      - Automatic API deployment: guides/autodeploy.md
      - Using Cert Manager: guides/cert-manager.md
      - Observability: guides/observability.md
      - Troubleshooting: guides/troubleshooting.md
  - Kusk CLI:
      - Installation: cli/overview.md
      - Install Kusk Gateway: cli/install-cmd.md
      - Generating API CRDs: cli/generate-cmd.md
      - Accessing Kusk Gateway's Dashboard: cli/dashboard-cmd.md
  - Kusk Dashboard:
      - Overview: dashboard/overview.md
      - Inspecting APIs: dashboard/inspecting-apis.md
      - Deploying APIs: dashboard/deploying-apis.md
  - 'Kusk Resources':
    - Overview: customresources/overview.md
    - API: customresources/api.md
    - Envoy Fleet: customresources/envoyfleet.md
    - Static Route: customresources/staticroute.md
  - 'Reference':
    - OpenAPI Extension: reference/extension.md
    - Architecture: reference/architecture.md
    - Dashboard API: reference/openapi.md
  - Contributing:
    - Development: 'contributing/development.md'
    - Roadmap: 'contributing/roadmap.md'

extra:
  analytics:
    provider: google
    property: UA-204665550-4

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our
      documentation and whether users find what they're searching for. With your consent, you're helping us to make our
      documentation better.

plugins:
 # - render_swagger
  - search

extra_css:
  - stylesheets/base.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2022 <a href="https://kubeshop.io">Kubeshop</a>
