site_name: Kusk Gateway
site_description: 'OpenAPI for Kubernetes done right'
site_author: 'Kubeshop Kusk team'
docs_dir: docs/
repo_name: 'kubeshop/kusk-gateway'
repo_url: 'https://github.com/kubeshop/kusk-gateway'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
  # features:
  #   - navigation.expand
nav:
  - Welcome: index.md
  - 'Getting Started': 
    - Install Kusk-gateway: getting-started/installation.md
    - Deploy an API: getting-started/deploy-an-api.md
    - Connect a Service to the API: getting-started/connect-a-service-to-the-api.md
  - 'Guides':
      - Mocking: guides/mocking.md
      - Validation: guides/validation.md
      - CORS: guides/cors.md
      - Routing: guides/routing.md
      - Timeouts: guides/timeouts.md
      - Automatic API deployment: guides/autodeploy.md
      - Using Cert Manager: guides/cert-manager.md
      - Troubleshooting: guides/troubleshooting.md
  - 'Reference':
    - Extension (x-kusk) docs: reference/extension.md
    - Kusk CLI: reference/kusk-cli.md
    - 'Custom Resources':
      - 'EnvoyFleet': reference/customresources/envoyfleet.md
      - 'API': reference/customresources/api.md
      - 'Static Route': reference/customresources/staticroute.md
    - Architecture: reference/architecture.md
  - Observability: observability.md
  - Contributing:
    - Development: 'contributing/development.md'
    - Roadmap: 'contributing/roadmap.md'

extra:
  analytics:
    provider: google
    property: UA-204665550-4

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our
      documentation and whether users find what they're searching for. With your consent, you're helping us to make our
      documentation better.

extra_css:
  - stylesheets/base.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>
