site_name: Kusk Gateway
site_description: 'OpenAPI for Kubernetes done right'
site_author: 'Kubeshop Kusk team'
docs_dir: docs/
repo_name: 'kubeshop/kusk-gateway'
repo_url: 'https://github.com/kubeshop/kusk-gateway'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
  # features:
  #   - navigation.expand
nav:
  - Welcome: index.md
  - 'Getting Started': 
    - Installation: getting-started/installation.md
    - Deploy an API: getting-started/deploy-an-api.md
  - 'Guides':
      - 'Using Cert Manager with Kusk Gateway': cert-manager.md
  - Roadmap: roadmap.md
  - For Developers: development.md
  - 'Reference':
    - Automatic API deployment: 'reference/automatic-api-deployment.md'
    - 'Custom Resources':
      - 'EnvoyFleet': reference/customresources/envoyfleet.md
      - 'API': reference/customresources/api.md
      - 'Static Route': reference/customresources/staticroute.md
    - Extension (x-kusk) docs: reference/extension.md
    - Architecture: reference/architecture.md
    - Kusk CLI: reference/kusk-cli.md
  - Troubleshooting: troubleshooting.md
  - Observability: observability.md
  - Contributing:
    - Development: 'contributing/development.md'
    - Roadmap: 'contributing/roadmap.md'

extra:
  analytics:
    provider: google
    property: UA-204665550-4

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our
      documentation and whether users find what they're searching for. With your consent, you're helping us to make our
      documentation better.

extra_css:
  - stylesheets/base.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>
