apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: kubeshop/kusk-gateway
      context: .
      docker:
        dockerfile: build/manager/Dockerfile
      platforms:
        - linux/amd64
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
manifests:
  rawYaml:
    - /tmp/skaffold/config-crd.yaml
    - /tmp/skaffold/config-default.yaml
    - /tmp/skaffold/config-map-metallb.yaml
deploy:
  kubectl:
    hooks:
      after:
        - host:
            command:
              - /bin/sh
              - -c
              - echo 'sleeping for 2 seconds before applying `config/samples/gateway_v1_envoyfleet.yaml`' && sleep 2
  kubeContext: kgw
---
apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
    - config/samples/gateway_v1_envoyfleet.yaml
deploy:
  kubectl: {}
  kubeContext: kgw
