apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    useBuildkit: true
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
    - image: kubeshop/kusk-gateway
      platforms: ["linux/amd64"]
      docker:
        dockerfile: build/manager/Dockerfile
      context: .
deploy:
  kubeContext: kgw
  kubectl:
    manifests:
      - /tmp/skaffold/config-crd.yaml
      - /tmp/skaffold/config-default.yaml
      - /tmp/skaffold/config-map-metallb.yaml
    hooks:
      after:
        - host:
            command:
              - /bin/sh
              - -c
              - echo 'sleeping for 2 seconds before applying `config/samples/gateway_v1_envoyfleet.yaml`' && sleep 2
---
apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubeContext: kgw
  kubectl:
    manifests:
      - config/samples/gateway_v1_envoyfleet.yaml
