apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manager.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: kubeshop/kusk-gateway
    newName: kubeshop/kusk-gateway
    newTag: latest
