apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: kusk-gateway-config

images:
- name: kusk-gateway
  newName: kusk-gateway
  newTag: dev
