apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manager.yaml
  - service.yaml
  - manager_configmap.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: kusk-gateway
    newName: kusk-gateway
    newTag: dev
patchesStrategicMerge:
  - manager_configmap.yaml
