apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: v1
data:
  ENABLE_LEADER_ELECTION: 'false'
  ENVOY_CONTROL_PLANE_BIND_ADDR: :18000
  HEALTH_PROBE_BIND_ADDR: :8081
  LOG_LEVEL: INFO
  METRICS_BIND_ADDR: :8080
  WEBHOOK_CERTS_DIR: /opt/manager/webhook/certs
  ANALYTICS_ENABLED: "false"
kind: ConfigMap
metadata:
  name: kusk-gateway-manager
  namespace: system
  labels:
    app.kubernetes.io/component: kusk-gateway-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusk-gateway-manager
  namespace: system
  labels:
    app.kubernetes.io/component: kusk-gateway-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: kusk-gateway-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kusk-gateway-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: kubeshop/kusk-gateway:latest
          name: manager
          envFrom:
            - configMapRef:
                name: kusk-gateway-manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: kusk-gateway-manager
      terminationGracePeriodSeconds: 10
