apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusk-gateway-manager
  namespace: system
  labels:
    app.kubernetes.io/component: kusk-gateway-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: kusk-gateway-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kusk-gateway-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /manager
          image: kusk-gateway:latest
          imagePullPolicy: IfNotPresent
          name: manager
          envFrom:
            - configMapRef:
                name: kusk-gateway-manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 256Mi
      serviceAccountName: kusk-gateway-manager
      terminationGracePeriodSeconds: 10
