apiVersion: v1
kind: Service
metadata:
  name: kusk-gateway-xds-service
  namespace: system
  labels:
    app.kubernetes.io/component: xds-service
spec:
  ports:
    - port: 18000
      name: xds
      targetPort: xds
  selector:
    app.kubernetes.io/component: kusk-gateway-manager
---
apiVersion: v1
kind: Service
metadata:
  name: kusk-gateway-validator-service
  namespace: system
  labels:
    app.kubernetes.io/component: validator-service
spec:
  ports:
    - port: 17000
      name: validator
      targetPort: validator
  selector:
    app.kubernetes.io/component: kusk-gateway-manager

---
apiVersion: v1
kind: Service
metadata:
  name: kusk-gateway-helper-service
  namespace: system
  labels:
    app.kubernetes.io/component: helper-service
spec:
  ports:
    - port: 18010
      name: helper-config
      targetPort: helper-config
  selector:
    app.kubernetes.io/component: kusk-gateway-manager
