apiVersion: v1
kind: Service
metadata:
  name: xds-service
  namespace: system
spec:
  ports:
    - port: 18000
      name: xds
      targetPort: xds
  selector:
    control-plane: controller-manager
