apiVersion: v1
kind: Service
metadata:
  name: kusk-gateway-manager-service
  namespace: system
  labels:
    app.kubernetes.io/component: xds-service
spec:
  ports:
    - port: 18000
      name: xds
      targetPort: xds
    - port: 19000
      name: auth
      targetPort: auth
      protocol: TCP
    - port: 17000
      name: validator
      targetPort: validator
  selector:
    app.kubernetes.io/component: kusk-gateway-manager
