apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: auth-static-route
spec:
  # should work with localhost, example.org
  hosts: ["localhost", "*"]
  paths:
    # Root goes to httpbin
    /static:
      get: &root_route
        route:
          upstream:
            host:
              hostname: auth-basic-http-authentication-service
              port: 9002
            rewrite:
              pattern: "^/$"
              substitution: "/get"
      # copying for all methods
      post: *root_route
      put: *root_route
      head: *root_route
    # /static -> /
    /static/redirect:
      get:
        redirect:
          path_redirect: "/static-root"
          response_code: 308
    # /get2 routed to k8s service httpbin in default namespace with rewrite to /get
    /static/get:
      get:
        route:
          upstream:
            service:
              name: httpbin
              namespace: default
              port: 8080
            rewrite:
              pattern: "^/get2$"
              substitution: "/get"
