apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: httpbin-sample
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  # should work with localhost, example.org
  hosts: ["localhost", "*"]
  upstream:
    service:
      name: httpbin
      namespace: default
      port: 8080
