apiVersion: gateway.kusk.io/v1
kind: StaticRoute
metadata:
  name: httpbin-sample
spec:
  # should work with localhost, example.org
  hosts: [ "localhost", "*"]
  paths:
  # Root goes to httpbin
    /: 
       get: &root_route
        route:
         backend:
            hostname: httpbin.default.svc.cluster.local
            port: 8080
            rewrite:
              pattern: "^/$"
              substitution: "/get"
       # copying for all methods
       post: *root_route
       put: *root_route
       head: *root_route
    # /static -> /
    /static: 
       get:
         redirect:
           path_redirect: "/"
           response_code: 308

