apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: httpbin-sample
spec:
  # should work with localhost, example.org
  hosts: [ "localhost", "*"]
  paths:
  # Root goes to httpbin
    /: 
      get: &root_route
        route:
          upstream:
            host:
              hostname: httpbin.default.svc.cluster.local
              port: 8080
          path:
            rewrite:
              pattern: "^/$"
              substitution: "/get"
      # copying for all methods
      post: *root_route
      put: *root_route
      head: *root_route
    # /static -> /
    /static: 
      get:
        redirect:
          path_redirect: "/"
          response_code: 308
    # /get2 routed to k8s service httpbin in default namespace with rewrite to /get
    /get2: 
      get:
        route:
          upstream:
            service:
              name: httpbin
              namespace: default
              port: 8080
          path:
            rewrite:
              pattern: "^/get2$"
              substitution: "/get"


