namespace: kusk-system

resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml


# Webhook configuration and names are hardcoded by controller-gen in manifests.yaml so we need to override paths and names with kustomize
patches:
- path: webhookpatch.json
  target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
- patch: |-
    - op: replace
      path: /metadata/name
      value: kusk-gateway-mutating-webhook-configuration
  target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
- path: webhookpatch.json
  target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
- patch: |-
    - op: replace
      path: /metadata/name
      value: kusk-gateway-validating-webhook-configuration
  target:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
