apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: auth-oauth2-oauth0-client-secret-ref
  namespace: default
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  spec: |
    openapi: 3.1.0
    info:
      title: "auth-oauth2-oauth0-client-secret-ref"
      description: "auth-oauth2-oauth0-client-secret-ref"
      version: "0.1.0"
    schemes:
    - http
    - https
    x-kusk:
      upstream:
        service:
          name: auth-oauth2-oauth0-client-secret-ref-go-httpbin
          namespace: default
          port: 80
      auth:
        scheme: oauth2
        oauth2:
          token_endpoint: https://kubeshop-kusk-gateway-oauth2.eu.auth0.com/oauth/token
          authorization_endpoint: https://kubeshop-kusk-gateway-oauth2.eu.auth0.com/authorize
          credentials:
            client_id: upRN78W8GzV4TwFRp0ekZfLx2UnqJJs8
            client_secret_ref:
              name: "auth-oauth2-oauth0-client-secret-ref-api"
              namespace: "oauth2-secrets"
          redirect_uri: /oauth2/callback
          redirect_path_matcher: /oauth2/callback
          signout_path: /oauth2/signout
          forward_bearer_token: true
          auth_scopes:
            - openid
    paths:
      "/":
        get:
          description: Returns GET data.
          operationId: "/get"
          responses: {}
      "/uuid":
        get:
          description: Returns UUID4.
          operationId: "/uuid"
          responses: {}
