# This kustomization is used to setup Debugging of kusk-gateway-manager in the cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

patchesStrategicMerge:
- manager_debug_patch.yaml

images:
- name: kusk-gateway
  newName: kusk-gateway
  newTag: dev-debug
