apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusk-gateway-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources: null
          # Disable healtchecks for the debuging image
          livenessProbe: null
          readinessProbe: null
          command:
            - /dlv
            - --listen=:40000
            - --headless=true
            - --api-version=2
            - exec
            - --accept-multiclient
            - --continue
            - /manager
            - --
            - "--health-probe-bind-address=:8081"
            - "--metrics-bind-address=127.0.0.1:8080"
            - "--leader-elect"
            - "-log-level=DEBUG"
            - "--development"
          args: []
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          ports:
            - containerPort: 40000
              name: debug
              protocol: TCP
