# This config starts goproxy in Host network, the container will bind to all interfaces,
# so any other container will be able to access it.
version: '3.8'
services:
  goproxy:
    network_mode: host
    container_name: goproxy
    image: goproxy/goproxy:latest
    restart: always
    expose:
      - 8085
    volumes:
      - goproxy:/go
    command:
      - -listen=0.0.0.0:8085
      - -proxy
      - https://goproxy.io
    #-exclude "*.corp.example.com,rsc.io/private"

volumes:
  goproxy:
    name: goproxy
    driver: local
