apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: test-traffic-splitting-api
  namespace: default
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  spec: |
    components: {}
    info:
      title: test-traffic-splitting-api
      description: test-traffic-splitting-api
      version: 0.1.0
    openapi: 3.0.0
    paths:
      "/uuid":
        get:
          description: Returns UUID4.
          operationId: "/uuid"
          responses: {}
    x-kusk:
      upstreams:
      - service:
          name: traffic-splitting-httpbin-1
          namespace: default
          port: 80
          weight: 50
      - service:
          name: traffic-splitting-httpbin-2
          namespace: default
          port: 80
          weight: 50
