/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
