/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ServicePortItem struct {
	Name string `json:"name"`

	NodePort int32 `json:"nodePort"`

	Port int32 `json:"port"`

	Protocol string `json:"protocol"`

	TargetPort string `json:"targetPort"`
}

// AssertServicePortItemRequired checks if the required fields are not zero-ed
func AssertServicePortItemRequired(obj ServicePortItem) error {
	elements := map[string]interface{}{
		"name":       obj.Name,
		"port":       obj.Port,
		"targetPort": obj.TargetPort,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseServicePortItemRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServicePortItem (e.g. [][]ServicePortItem), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServicePortItemRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServicePortItem, ok := obj.(ServicePortItem)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServicePortItemRequired(aServicePortItem)
	})
}
