/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type StaticRouteItemFleet struct {
	Name string `json:"name"`

	Namespace string `json:"namespace"`
}

// AssertStaticRouteItemFleetRequired checks if the required fields are not zero-ed
func AssertStaticRouteItemFleetRequired(obj StaticRouteItemFleet) error {
	elements := map[string]interface{}{
		"name":      obj.Name,
		"namespace": obj.Namespace,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseStaticRouteItemFleetRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StaticRouteItemFleet (e.g. [][]StaticRouteItemFleet), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStaticRouteItemFleetRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStaticRouteItemFleet, ok := obj.(StaticRouteItemFleet)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStaticRouteItemFleetRequired(aStaticRouteItemFleet)
	})
}
