/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type InlineObject1 struct {
	Name string `json:"name,omitempty"`

	Namespace string `json:"namespace,omitempty"`

	EnvoyFleetName string `json:"envoyFleetName,omitempty"`

	EnvoyFleetNamespace string `json:"envoyFleetNamespace,omitempty"`

	Openapi string `json:"openapi,omitempty"`
}

// AssertInlineObject1Required checks if the required fields are not zero-ed
func AssertInlineObject1Required(obj InlineObject1) error {
	return nil
}

// AssertRecurseInlineObject1Required recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of InlineObject1 (e.g. [][]InlineObject1), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseInlineObject1Required(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aInlineObject1, ok := obj.(InlineObject1)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertInlineObject1Required(aInlineObject1)
	})
}
