apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: system
  labels:
    app: envoy
spec:
  selector:
    matchLabels:
      app: envoy
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - command:
        - envoy
        args:
        - -c
        - /etc/envoy/envoy.yaml
        image: envoyproxy/envoy-dev:latest
        name: envoy
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: envoy
  name: envoy
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: envoy
  type: LoadBalancer
status:
  loadBalancer: {}
