apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kusk-gateway
    app.kubernetes.io/component: metrics-service
    app.kubernetes.io/instance: kusk-gateway-development
  name: kusk-gateway-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/name: kusk-gateway
    app.kubernetes.io/component: kusk-gateway-manager
    app.kubernetes.io/instance: kusk-gateway-development
