# permissions for end users to view envoyfleet.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kusk-gateway-envoyfleet-viewer-role
rules:
- apiGroups:
  - gateway.kusk.io
  resources:
  - envoyfleet
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.kusk.io
  resources:
  - envoyfleet/status
  verbs:
  - get
