apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kusk-gateway-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kusk-gateway-manager-role
subjects:
- kind: ServiceAccount
  name: kusk-gateway-manager
  namespace: system
