apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: traffic-splitting-api-1
  namespace: kusk-system
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  spec: |
    components: {}
    info:
      title: traffic-splitting-api-1
      version: 0.1.0
    openapi: 3.0.0
    paths:
      "/uuid":
        get:
          description: Returns UUID4.
          operationId: "/uuid"
          responses: {}
      /hello:
        get:
          responses:
            "200":
              content:
                application/json:
                  example:
                    message: Hello from a mocked response!
                  schema:
                    properties:
                      message:
                        type: string
                    type: object
              description: A simple hello world!
      /validated:
        post:
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
          responses:
            "200":
              content:
                text/plain:
                  example: Hello mocked Kusk!
                  schema:
                    type: string
              description: ""
    x-kusk:
      cors:
        methods:
        - GET
        - POST
        origins:
        - '*'
      upstreams:
      - service:
          name: httpbin1
          namespace: default
          port: 80
          weight: 50
      - service:
          name: httpbin2
          namespace: default
          port: 80
          weight: 50
