apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: envoy
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy-config.yaml
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
