---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-authz-http-basic-auth
  name: ext-authz-http-basic-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-http-basic-auth
  template:
    metadata:
      labels:
        app: ext-authz-http-basic-auth
    spec:
      containers:
        - image: docker.io/kubeshop/kusk-ext-authz-http-service
          name: ext-authz-http-basic-auth
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-authz-http-basic-auth
  name: ext-authz-http-basic-auth
spec:
  ports:
    - port: 80
      targetPort: 9002
  selector:
    app: ext-authz-http-basic-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-authz-http-basic-auth-httpbin
  name: ext-authz-http-basic-auth-httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-http-basic-auth-httpbin
  template:
    metadata:
      labels:
        app: ext-authz-http-basic-auth-httpbin
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          name: ext-authz-http-basic-auth-httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-authz-http-basic-auth-httpbin
  name: ext-authz-http-basic-auth-httpbin
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ext-authz-http-basic-auth-httpbin
