FROM golang

RUN apt-get update \
    && apt-get install --no-install-recommends -y netcat \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*

WORKDIR /go/go-control-plane
COPY go-control-plane/go.mod go-control-plane/go.sum /go/go-control-plane/
RUN go mod download
COPY go-control-plane /go/go-control-plane
RUN go build -race -o go-control-plane .
ENTRYPOINT [ "/go/go-control-plane/go-control-plane"]
CMD [ "-debug", "$@" ]
