apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: staticroute-sample
spec:
  hosts: [ "*" ]
  paths:
    /: 
       get:
        route:
         backend:
            hostname: blablab
            port: 8080
    /static: 
       get:
         redirect:
           port_redirect: 81