---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-authz-http-basic-auth-openapi-path-with-auth
  name: ext-authz-http-basic-auth-openapi-path-with-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-http-basic-auth-openapi-path-with-auth
  template:
    metadata:
      labels:
        app: ext-authz-http-basic-auth-openapi-path-with-auth
    spec:
      containers:
        - image: docker.io/kubeshop/ext-authz-http-basic-auth
          name: ext-authz-http-basic-auth
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-authz-http-basic-auth-openapi-path-with-auth
  name: ext-authz-http-basic-auth-openapi-path-with-auth
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ext-authz-http-basic-auth-openapi-path-with-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-openapi-path-with-auth-httpbin
  name: test-openapi-path-with-auth-httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-openapi-path-with-auth-httpbin
  template:
    metadata:
      labels:
        app: test-openapi-path-with-auth-httpbin
    spec:
      containers:
        - image: docker.io/mccutchen/go-httpbin:v2.4.1
          name: test-openapi-path-with-auth-httpbin
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-openapi-path-with-auth-httpbin
  name: test-openapi-path-with-auth-httpbin
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: test-openapi-path-with-auth-httpbin
