---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-authz-http-service
  name: ext-authz-http-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-http-service
  template:
    metadata:
      labels:
        app: ext-authz-http-service
    spec:
      containers:
        - image: docker.io/kubeshop/kusk-ext-authz-http-service:v0.0.1
          name: ext-authz-http-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin:latest
          name: httpbin
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
