---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ext-authz-http-service
  name: ext-authz-http-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz-http-service
  template:
    metadata:
      labels:
        app: ext-authz-http-service
    spec:
      containers:
        - image: docker.io/kubeshop/kusk-ext-authz-http-service
          name: ext-authz-http-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ext-authz-http-service
  name: ext-authz-http-service
spec:
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: ext-authz-http-service
