---
apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: websocket-backend
spec:
  # should work with localhost, example.org
  hosts: [ "localhost", "*"]
  paths:
  # Root goes to frontend service
    /staticwebsocket: 
       get:
        route:
          websocket: true
          upstream:
              service:
                namespace: default
                name: ws-server
                port: 80
