apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: examples-cors-2
  namespace: default
spec:
  fleet:
    name: kusk-gateway-envoy-fleet
    namespace: kusk-system
  spec: |
    openapi: 3.1.0
    servers:
      - url: http://localhost:8080
    info:
      title: examples-cors-2
      description: examples-cors-2
      version: 0.1.0
    x-kusk:
      cors:
        origins:
          - "https://example.org"
          - "https://httpbin.org"
        methods:
          - GET
          - POST
        credentials: true
        max_age: 86200
      upstream:
        service:
          name: hello-world
          namespace: default
          port: 8080
    paths:
      /hello:
        get:
          summary: Return a simple hello world!
          responses:
            "200":
              description: A simple hello world!
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
