name: goreleaser
on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: setup-goreleaser-environment-variables
        run: |
          echo "VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v1.9.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          VERSION: ${{ env.VERSION }}
          TELEMETRY_TOKEN: ${{ secrets.TELEMETRY_TOKEN }}
