apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-custom-path
  name: auth-custom-path
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-custom-path
  template:
    metadata:
      labels:
        app: auth-custom-path
    spec:
      containers:
        - image: docker.io/banaioltd/kubeshop-io-auth-custom-path:v0.1.0
          name: auth-custom-path
          # imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-custom-path
  name: auth-custom-path
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: auth-custom-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-custom-path-httpbin
  name: auth-custom-path-httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-custom-path-httpbin
  template:
    metadata:
      labels:
        app: auth-custom-path-httpbin
    spec:
      containers:
        - image: docker.io/mccutchen/go-httpbin:v2.4.1
          name: auth-custom-path-httpbin
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-custom-path-httpbin
  name: auth-custom-path-httpbin
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: auth-custom-path-httpbin
