apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: test-rate-limit
spec:
  fleet:
    name: default
    namespace: default
  # service name and port should be specified inside x-kusk annotation
  spec: |
    components: {}
    info:
      title: simple-api
      version: 0.1.0
    openapi: 3.0.0
    x-kusk:
      cors:
        methods:
        - GET
        - POST
        origins:
        - '*'
      mocking:
        enabled: true
    paths:
      /rate_limit:
        get:
          x-kusk:
            rate_limit:
              requests_per_unit: 2
              unit: minute
          responses:
            "200":
              content:
                application/json:
                  example:
                    message: rate-limited mocked response.
                  schema:
                    properties:
                      message:
                        type: string
                    type: object
              description: A simple hello world!
