apiVersion: gateway.kusk.io/v1alpha1
kind: StaticRoute
metadata:
  name: sample
  namespace: default
spec:
  fleet:
    name: default
    namespace: default
  auth:
    oauth2:
      token_endpoint: https://kubeshop-kusk-gateway-oauth2.eu.auth0.com/oauth/token
      authorization_endpoint: https://kubeshop-kusk-gateway-oauth2.eu.auth0.com/authorize
      credentials:
        client_id: "upRN78W8GzV4TwFRp0ekZfLx2UnqJJs8"
        client_secret: "Z6MX7NreJumWLmf6unsQ5uiEUrTBxfNtqG9Vy5Kjktnvfj-_fRCBO9EU1mL1YzAJ"
      redirect_uri: /oauth2/callback
      redirect_path_matcher: /oauth2/callback
      signout_path: /oauth2/signout
      forward_bearer_token: true
      auth_scopes:
        - openid
      pass_through_matcher:
        - /version
  paths:
    /:
      get:
        route:
          upstream:
            service:
              name: frontend-app-svc
              namespace: default
              port: 3000
    /version:
      get:
        route:
          upstream:
            service:
              name: version-svc
              namespace: default
              port: 80
