apiVersion: gateway.kusk.io/v1alpha1
kind: API
metadata:
  name: ext-auth-http-oauth2
  namespace: default
spec:
  fleet:
    name: default
    namespace: default
  # service name and port should be specified inside x-kusk annotation
  spec: |
    openapi: 3.0.0
    info:
      title: ext-auth-http-oauth2
      description: ext-auth-http-oauth2
      version: '0.0.1'
    schemes:
    - http
    - https
    x-kusk:
      upstream:
        service:
          name: ext-auth-http-oauth2-httpbin
          namespace: default
          port: 80
      auth:
        scheme: oauth2
        oauth2:
          token_endpoint: https://oauth2.googleapis.com/token
          authorization_endpoint: https://accounts.google.com/o/oauth2/auth
          credentials:
            client_id: 636763127632-81urtve1c2bd56aa2g7e8aodlqqq8gvo.apps.googleusercontent.com
            client_secret: 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
            token_secret: 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
            hmac_secret: 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
          redirect_uri: http://localhost
          redirect_path_matcher: /oauth2/callback
          signout_path: /oauth2/signout
          forward_bearer_token: true
          auth_scopes:
            - user
            - openid
          resources:
            - user
            - openid
    paths:
      "/":
        get:
          description: Returns GET data.
          operationId: "/get"
          responses: {}
      "/uuid":
        get:
          description: Returns UUID4.
          operationId: "/uuid"
          responses: {}
