apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: kubeshop/todobackend-backend
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
          name: http
