apiVersion: v1
kind: Namespace
metadata:
  name: auth-jwt-oauth0-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-oauth0-secrets
  namespace: auth-jwt-oauth0-secrets
type: Opaque
data:
  client_secret: "base64"
