name: build and test

# Cancel any pending or running workflow if the new one is triggered
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [ main, add-build_args ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test ANALYTICS_TRACKING_ID=${{ secrets.ANALYTICS_TRACKING_ID }} ANALYTICS_API_KEY=${{ secrets.ANALYTICS_API_KEY }}
