name: mkdocs

# Cancel any pending or running workflow if the new one is triggered
concurrency:
  group: "mkdocs"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-render-swagger-plugin
      - run: mkdocs gh-deploy --force
