name: Release Kusk Gateway

on:
  push:
    # branches:
      # - 'main'
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:

  release:
    name: Create and upload release-artifacts
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker metadata for Kusk Gateway
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/kusk-gateway
          tags: |
            type=semver,pattern=v{{version}}
            type=sha
          flavor: |
            latest=true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Run GoReleaser to publish release notes
        if: github.event_name != 'pull_request'
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
