name: Release Kusk Gateway

# Cancel any pending or running workflow if the new one is triggered
concurrency:
  group: "release"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    tags: 
      # - "v[0-9]+.[0-9]+.[0-9]+"
      # - "v[0-9]+.[0-9]+.[0-9]+-*"
      - "test-*"

jobs:

  release:
    name: Create and upload release-artifacts
    # if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # -
      #   name: Login to DockerHub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Docker metadata for Kusk Gateway
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: kubeshop/kusk-gateway
      #     tags: |
      #       type=semver,pattern=v{{version}}
      #       type=sha
      #     flavor: |
      #       latest=true
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      # -
      #   name: Run GoReleaser to publish release notes
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     distribution: goreleaser
      #     version: latest
      #     args: release --rm-dist --skip-sign
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      -
        name: Check if we have modified CRDs or RBAC between 2 last tags
        run: |
          CHANGED_FILES_STATS=$(git diff  $(git rev-list --tags --max-count=2) --stat config/crd config/rbac | tail -1)
          echo "Changed CRD or RBAC files: ${CHANGED_FILES_STATS}"
          git diff  $(git rev-list --tags --max-count=2) --stat config/crd config/rbac

          # SECURITY: disable command workflow processing
          # https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

          # This will set global environment variable CRDS_CHANGED to true or false
          if [[ -n "$CHANGED_FILES_STATS" ]]; then
            echo "CRDS_CHANGED=true" >> $GITHUB_ENV
          else
            echo "CRDS_CHANGED=false" >> $GITHUB_ENV
          fi

          # SECURITY: enable workflow command processing
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      -
        name: Notify Slack channel if CRDs or RBAC changes
        uses: rtCamp/action-slack-notify@v2
        if: ${{ env.CRDS_CHANGED == 'true' }}
        env:
          SLACK_CHANNEL: testmessages
          # yellow
          SLACK_COLOR: "#FFFF00"
          SLACK_ICON: https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg
          SLACK_TITLE: Kusk Gateway Release ${{ github.ref }} has changed CRDs or RBAC
          SLACK_MESSAGE: "kusk-gateway Helm chart won't be updated automatically. Merge the changes in manually in helm-charts repository."
          SLACK_USERNAME: GitHub
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Kubeshop --> Kusk Gateway"
